version: "3"
services:
  node-app:
    container_name: nodejs
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  mongo:
    image: mongo:4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mcmzrc
      - MONGO_INITDB_ROOT_PASSWORD=zrenjaninac
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    container_name: redis

volumes:
  mongo-db:
