version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    # container_name: nodejs
    build: .
    environment:
      - PORT=5000
    depends_on:
      - mongo
  mongo:
    image: mongo:4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mcmzrc
      - MONGO_INITDB_ROOT_PASSWORD=zrenjaninac
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    container_name: redis

volumes:
  mongo-db:
